### ISSUE TITLE
fd:: Invalid data found when processing input

### ISSUE THREAD

**Issue by arkadesOrg** [animafps/teres#73]
running` teres -n file.mp4` throws the error mentioned above, which is an ffmpeg error.

**Comment by animafps** [comment]
please give more information, like version and config

**Comment by arkadesOrg** [comment]
I just installed the teres-git version on archlinux. I found that teres generates this command `ffmpeg -loglevel error -hide_banner -nostats -i - -i subway-timeramp.mov -map 0:v -map 1:a? -c:v h264_nvenc -preset p7 -qp 18 -c:a aac -b:a 320k -movflags +faststart subway-timeramp_blur.mp4` where I guess `-i -` is the problem.

Also the default config file contains `container = mp4` instead of `container = "mp4"`

Thanks for the quick response!

**Comment by arkadesOrg** [comment]
I quickfixed the issue with a `/bin/ffmpeg`-substitute script to remove `-i -` from the generated command arguments before passing it to the real ffmpeg. But now the `vspipe` subprocess runs forever as a zombi consuming 25% cpu (1 core)

**Comment by animafps** [comment]
That breaks it cause -i - is the argument that inputs the data so ffmpeg is getting nothing

**Comment by animafps** [comment]
vspipe is the issue here most likely in the config, what is your config or change vspipes' log level

**Comment by animafps** [comment]
stale

**Comment by markusressel** [comment]
I am getting the same error, when trying to process some DJI 03 Air Unit recordings in 4k 60.
Can we reopen this or should I create a new issue? I can also try to add more info if you show me how :)

**Comment by animafps** [comment]
its a generic error mostly from an issue with vapoursynth

best way to debug is when it hangs like that to leave it open then from another terminal

`cd /#path to the video#/.teres-temp/`
`vspipe #random#.vpy .`

inserting #path to the video# with the path and #random# with the generated file name that ends with .vpy

**Comment by animafps** [comment]
also platform and version is very useful

**Comment by markusressel** [comment]
```
> uname -a
Linux Silver 6.4.11-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 19 Aug 2023 15:38:34 +0000 x86_64 GNU/Linux

> uname -mrs
Linux 6.4.11-arch2-1 x86_64

> teres -V
teres 0.3.2
```

Its an Arch Linux, package is:
```
aur/teres 0.3.3-1 (+1 0.00) (Installed)
```

Hardware:
Ryzen 7 5800X
AMD Radeon RX 6700 XT
64GB DDR4

```
> teres -v -n DJI_0127_stabilized.mp4

    ████████╗███████╗██████╗ ███████╗███████╗
    ╚══██╔══╝██╔════╝██╔══██╗██╔════╝██╔════╝
       ██║   █████╗  ██████╔╝█████╗  ███████╗
       ██║   ██╔══╝  ██╔══██╗██╔══╝  ╚════██║
       ██║   ███████╗██║  ██║███████╗███████║
       ╚═╝   ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝

Processing DJI_0127_stabilized.mp4
fd:: Invalid data found when processing input
```

```
> vspipe 55059.vpk .
Script evaluation failed:
Python exception: No module named 'adjust'

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
  File "src/cython/vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate
  File "55059.vpk", line 3, in <module>
    import havsfunc as haf
  File "/usr/lib/python3.11/site-packages/havsfunc.py", line 7, in <module>
    import adjust
ModuleNotFoundError: No module named 'adjust'
```

I am guessing this is not the actual error, but something about vspipe isn't working on my system? :thinking:

**Comment by animafps** [comment]
oh lol forgot to vendor adjust.py

https://github.com/animafps/teres/raw/api/plugins/adjust.py
install to /usr/lib/python3.11/site-packages/

**Comment by markusressel** [comment]
I did change my config to use the GPU though. I really don't want to encode using the CPU, since that will probably take hours instead of minutes :sweat_smile:

**Comment by markusressel** [comment]
Seems like the new error is related to GPU encoding. If I disable GPU encoding, it _seems_ to work correctly (not fully processed yet).

**Comment by animafps** [comment]
can you post the new error

**Comment by markusressel** [comment]
I posted above, sorry for the confusion.
This is the error I am talking about:

```
Processing DJI_0127_stabilized.mp4
 [DJI_0127_stabilized.mp4] ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% 2d 18:03:27[h264_amf @ 0x558355992440] DLL libamfrt64.so.1 failed to open
[vost#0:0/h264_amf @ 0x558355992140] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

**Comment by markusressel** [comment]
Looking at this: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/248

I might have to install the "amd pro" drivers?
Although that would be a bit confusing to me, as I have already used other tools (like Gyroflow) to encode on my GPU and it worked fine with my current driver setup.

**Comment by animafps** [comment]
well its using the proprietary gpu codec atm but soon will implement a better solution to maybe use vaapi but that is just a support issue on teres end

if no other issues marking as closed

**Comment by markusressel** [comment]
Alright, thx for the support!

**Comment by couleurm** [comment]
for now u can use x264 or a lossless codec

**Comment by hir0xygen** [comment]
Currently encountering this issue trying to run teres on a file.

> Artix Linux x86_64 (Arch based)
> Linux 6.11.7-zen1-1-zen
> 
> Ryzen 7 3700X
> Nvidia GeForce RTX 4080 Super
> 32GB DDR4

```
$ uname -a
Linux artix 6.11.7-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 09 Nov 2024 23:43:05 +0000 x86_64 GNU/Linux

$ teres --version
teres 0.3.5

$ paru -Q teres
teres-git 0.3.5.r5.g0b059d2-1
```

```
$ teres -n doors.mp4

    ████████╗███████╗██████╗ ███████╗███████╗
    ╚══██╔══╝██╔════╝██╔══██╗██╔════╝██╔════╝
       ██║   █████╗  ██████╔╝█████╗  ███████╗
       ██║   ██╔══╝  ██╔══██╗██╔══╝  ╚════██║
       ██║   ███████╗██║  ██║███████╗███████║
       ╚═╝   ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝

Processing doors.mp4
[in#0 @ 0x5cfcb37b1f00] Error opening input: Invalid data found when processing input
Error opening input file -.
Error opening input files: Invalid data found when processing input
```

```
$ ffprobe doors.mp4
ffprobe version n7.1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 14.2.1 (GCC) 20240910
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-frei0r --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libdvdnav --enable-libdvdread --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librsvg --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-vapoursynth --enable-version3 --enable-vulkan
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'doors.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf61.7.100
  Duration: 00:00:10.14, start: 0.000000, bitrate: 8668 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 2560x1440 [SAR 1:1 DAR 16:9], 8508 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 4.0, fltp, 267 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
```


The issue **persists** when transcoding the file to H.264, here's the ffprobe of the H.264 transcoded file for reference (same error in teres with this one):


```
$ ffprobe doors_h264.mp4
ffprobe version n7.1 Copyright (c) 2007-2024 the FFmpeg developers
  built with gcc 14.2.1 (GCC) 20240910
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-frei0r --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libdvdnav --enable-libdvdread --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librsvg --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-vapoursynth --enable-version3 --enable-vulkan
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'doors_h264.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.7.100
  Duration: 00:00:10.14, start: 0.000000, bitrate: 7137 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 2560x1440 [SAR 1:1 DAR 16:9], 6953 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.19.100 libx264
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 4.0, fltp, 267 kb/s (default)
      Metadata:
        handler_name    : SoundHandler
        vendor_id       : [0][0][0][0]
```
